# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7bacb98c7176714e416f5ac6b9b83420333cf5564f45cd334693ccef1901febfc84c9f8bc85c75f9e19f447993bb2bd7abfa866fc672ba255580dabe6cea46bb

test:
  secret_key_base: 08150154f196e6fc1b5546e58d5ba3998028d85ffacf38c33e257b8e8a7468bb4a7e2f1fd9f84310f188c6ea07010fb1f2bc041841b688917edbee46c7028b65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
